language: node_js
node_js:
  - '12.8.1'

cache:
  - npm

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  skip-cleanup: true
  local_dir: dist
  on:
    branch: master
